name: Linux Ubuntu
on:
  push:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/ubuntu.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: 5.15.2
          cached: 'false'
          modules: qtwebengine
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          qmake
          make
      - name: package dependencies
        run: |
          sudo apt-get install libxcb-icccm4 libxcb-image0
      - name: package
        run: |
          mkdir deploy
          cp ${{github.event.repository.name}} deploy/
          cp LICENSE* deploy/
          cp *md deploy/
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage deploy/${{github.event.repository.name}} -appimage -verbose=2 -unsupported-allow-new-glibc
      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.repository.name}}-${{ matrix.qt_arch }}
          path: ${{github.workspace}}/deploy/
