name: Linux Ubuntu
on:
  push:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/ubuntu.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: 5.15.2
          cached: 'false'
          modules: qtwebengine
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set Env
        run: |
          export VERSION=$(grep -o '".*"' src/version.h | sed 's/"//g')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: build ubuntu
        run: |
          qmake
          make
      - name: package dependencies
        run: |
          sudo apt update
          sudo apt install -y libgl-dev libx11-dev libxkbcommon-x11-dev libxcb-image0-dev libxcb-icccm4-dev libssl-dev libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0
          sudo apt install -y libprotobuf-dev protobuf-compiler protobuf-c-compiler libgrpc++-dev protobuf-compiler-grpc ninja-build fcitx-frontend-qt5 libcurl4-openssl-dev
      #- name: package
        #run: |
          #make INSTALL_ROOT=appdir -j2 install ; find appdir/
          #wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          #chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          #./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage -verbose=2 -unsupported-allow-new-glibc
      #- uses: actions/upload-artifact@v2
        #with:
          #name: ${{github.event.repository.name}}-${VERSION}-${{ matrix.qt_arch }}.AppImage
          #file: ${{github.event.repository.name}}-${VERSION}-x86_64.AppImage
